### ISSUE TITLE
Extend the DynamoDB table with sort key containing date and time.

### ISSUE THREAD

**Issue by DanielGeshdo** [curityio/aws-token-publisher#2]
Hi Curity Team,

I would like to have a clean-up job remove expired tokens form this table, but this is difficult with the existing table structure.

Can you and an sort key with date and time?

If you have any questions please don't hesitate to contact me.

Kind regards
Daniel

**Comment by iggbom** [comment]
The data type of expiration is now Number instead of String. This allows for the DynamoDB TTL functionality to be used to automatically purge the items in the table when the expiration is older than current time.
